/**
 * Git Commit Service
 * Automatically commits and pushes saved skills to GitHub repository.
 *
 * @deprecated This service is no longer used by Skills Factory.
 * Skills Factory now saves drafts locally to draft-skills/ without git operations.
 * This file is kept for potential future use or other features.
 */

const { execSync } = require("child_process");
const path = require("path");

const SKILLS_REPO_PATH = path.join(__dirname, "../../../../skillet-skills");

/**
 * Execute git command in the skills repository
 * @param {string} command - Git command to execute
 * @returns {string} Command output
 */
function executeGitCommand(command) {
  try {
    const output = execSync(command, {
      cwd: SKILLS_REPO_PATH,
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    return output.trim();
  } catch (error) {
    throw new Error(`Git command failed: ${error.message}`);
  }
}

/**
 * Check if git is available and repository is initialized
 * @returns {boolean} True if git is available
 */
function isGitAvailable() {
  try {
    executeGitCommand("git --version");
    executeGitCommand("git rev-parse --git-dir");
    return true;
  } catch (error) {
    console.warn(
      "Git not available or repository not initialized:",
      error.message,
    );
    return false;
  }
}

/**
 * Configure git user if not already set
 */
function ensureGitConfig() {
  try {
    // Check if user.name is set
    try {
      executeGitCommand("git config user.name");
    } catch {
      // Set default if not configured
      executeGitCommand('git config user.name "Skillet Skills Factory"');
    }

    // Check if user.email is set
    try {
      executeGitCommand("git config user.email");
    } catch {
      // Set default if not configured
      executeGitCommand('git config user.email "skills-factory@skillet.local"');
    }
  } catch (error) {
    console.warn("Could not configure git user:", error.message);
  }
}

/**
 * Commit and push a new skill to the repository
 * @param {string} filename - Name of the skill file
 * @param {string} category - Skill category
 * @returns {Promise<Object>} Commit result
 */
async function commitAndPushSkill(filename, category) {
  if (!isGitAvailable()) {
    return {
      success: false,
      message: "Git not available - skill saved locally only",
      committed: false,
    };
  }

  try {
    // Ensure git config is set
    ensureGitConfig();

    // Stage the new skill file
    const skillPath = `skills/${filename}`;
    executeGitCommand(`git add "${skillPath}"`);

    // Also stage skill-index.json if it was updated
    try {
      executeGitCommand("git add metadata/skill-index.json");
    } catch (error) {
      // Index file might not have changed, that's okay
    }

    // Check if there are changes to commit
    try {
      const status = executeGitCommand("git status --porcelain");
      if (!status) {
        return {
          success: true,
          message: "No changes to commit",
          committed: false,
        };
      }
    } catch (error) {
      // Continue with commit
    }

    // Create commit message
    const commitMessage = `Add skill: ${category}/${filename.replace(".md", "")}

Generated by Skills Factory
Category: ${category}
File: ${filename}`;

    // Commit the changes
    executeGitCommand(`git commit -m "${commitMessage}"`);

    // Try to push to remote
    try {
      executeGitCommand("git push origin main");

      return {
        success: true,
        message: "Skill committed and pushed to GitHub",
        committed: true,
        pushed: true,
      };
    } catch (pushError) {
      // Push failed, but commit succeeded
      console.warn("Push failed:", pushError.message);

      return {
        success: true,
        message:
          "Skill committed locally (push failed - check remote configuration)",
        committed: true,
        pushed: false,
        error: pushError.message,
      };
    }
  } catch (error) {
    console.error("Git commit error:", error.message);

    return {
      success: false,
      message: `Git operation failed: ${error.message}`,
      committed: false,
      error: error.message,
    };
  }
}

/**
 * Get current git status
 * @returns {Object} Git status information
 */
function getGitStatus() {
  if (!isGitAvailable()) {
    return {
      available: false,
      message: "Git not available",
    };
  }

  try {
    const branch = executeGitCommand("git rev-parse --abbrev-ref HEAD");
    const status = executeGitCommand("git status --porcelain");
    const hasChanges = status.length > 0;

    let remoteUrl = "Not configured";
    try {
      remoteUrl = executeGitCommand("git config --get remote.origin.url");
    } catch {
      // Remote not configured
    }

    return {
      available: true,
      branch,
      hasChanges,
      remoteUrl,
      message: hasChanges
        ? "Uncommitted changes present"
        : "Working tree clean",
    };
  } catch (error) {
    return {
      available: true,
      error: error.message,
      message: "Could not get git status",
    };
  }
}

module.exports = {
  commitAndPushSkill,
  isGitAvailable,
  getGitStatus,
};

// Made with Bob - Auto-commit to GitHub
